# -*- coding: utf-8 -*-
"""knn.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5ESWigHz7RaaKAtGBV1UX8v24ciGiJ0
"""

# from google.colab import files
# uploaded = files.upload()

# !pip install scikit-learn pandas

from preprocessing import BikePreprocessor
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, classification_report
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, classification_report

#running the preprocessing once
#low demand >> high demand, so we pick F1
from preprocessing import BikePreprocessor

pre = BikePreprocessor(
    target='increase_stock',
    input_file='training_data_ht2025.csv',
    output_dir='.'
)

pre.logreg()



#loading the preprocessed data
X_train = pd.read_csv("X_train.csv")
X_test  = pd.read_csv("X_test.csv")
y_train = pd.read_csv("y_train.csv", header=None).iloc[:, 0]
y_test  = pd.read_csv("y_test.csv", header=None).iloc[:, 0]

#defining the hyperparameter grid and CV strategy
param_grid = {
    "n_neighbors": [3, 5, 7, 9, 11],
    "weights": ["uniform", "distance"],
    "p": [1, 2],
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
knn = KNeighborsClassifier()

grid = GridSearchCV(
    knn,
    param_grid,
    cv=cv,
    scoring="f1",
    n_jobs=-1,
)


grid.fit(X_train, y_train)
best_knn = grid.best_estimator_
print("Best params:", grid.best_params_)

y_pred = best_knn.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))
print(classification_report(y_test, y_pred))